In [1]:
import shap
import numpy.random
import numpy.linalg
import numpy as np
from lime.lime_text import LimeTextExplainer

In [2]:

def predict_txt(txt_list):
    out = []
    data = np.zeros((len(txt_list),4))
    out = []
    for i in range(len(txt_list)):
        words = txt_list[i].split()
        prob = 0.0
        if "fever" in words and "congestion" in words and "cough" in words:
            prob += 0.60
        out.append(prob)
    out = np.array(out)
    return np.transpose(np.vstack([1-out, out]))

explainer = LimeTextExplainer(class_names=["a", "b"])

exp = explainer.explain_instance("fever cough congestion headache", predict_txt, num_features=3)
exp.as_list()

/Users/slund1/anaconda3/lib/python3.5/re.py:203: FutureWarning: split() requires a non-empty pattern match.
  return _compile(pattern, flags).split(string, maxsplit)


[('headache', -0.16797374846574542),
 ('congestion', 0.1355913938980613),
 ('fever', 0.1301733100704961)]

In [35]:
def gen_input(N):
    x = np.ones((1,N))
    x[0,0] = np.random.choice([0,0,4,5,6])
    x[0,1] = np.random.choice([0,0,4,5,6])
    x[0,2] = np.random.choice([0,0,4,5,6])
    x[0,int(N/2)] = np.random.choice([0,0,4,5,6])
    x[0,int(N/2) + 1] = np.random.choice([0,0,4,5,6])
    return x

In [36]:
np.max(np.ones((3,5)),1)

array([ 1.,  1.,  1.])

In [37]:
def f(x):
    halfway = int(x.shape[1]/2)
    return np.max(x[:,0:3],1) + np.max(x[:,halfway:halfway+2],1)

In [41]:
x = gen_input(14)
x

array([[ 0.,  4.,  6.,  1.,  1.,  1.,  1.,  0.,  4.,  1.,  1.,  1.,  1.,
         1.]])

In [42]:
x

array([[ 0.,  4.,  6.,  1.,  1.,  1.,  1.,  0.,  4.,  1.,  1.,  1.,  1.,
         1.]])

In [43]:
exp = shap.KernelExplainer(f, np.zeros((1,14)))
truth = exp.explain(x, nsamples=100000).effects

nsamples 4094


In [44]:
truth

array([ 0.,  2.,  4.,  0.,  0.,  0.,  0.,  0.,  4.,  0.,  0.,  0.,  0.,  0.])

In [45]:
f(x)

array([ 10.])

In [46]:
shap_performance = []
for nsamples in range(20,2000,100):
    exp = shap.KernelExplainer(f, np.zeros((1,14)))
    shap_effects = exp.explain(x, nsamples=nsamples).effects
    print(nsamples, shap_effects)
    shap_performance.append(np.linalg.norm(truth - shap_effects))

nsamples 20
20 [ 0.  2.  4.  0.  0.  0.  0.  0.  4.  0.  0.  0.  0.  0.]
nsamples 120
120 [ 0.  2.  4.  0.  0.  0.  0.  0.  4.  0.  0.  0.  0.  0.]
nsamples 220
220 [ 0.  2.  4.  0.  0.  0.  0.  0.  4.  0.  0.  0.  0.  0.]
nsamples 320
320 [ 0.  2.  4.  0.  0.  0.  0.  0.  4.  0.  0.  0.  0.  0.]
nsamples 420
420 [ 0.  2.  4.  0.  0.  0.  0.  0.  4.  0.  0.  0.  0.  0.]
nsamples 520
520 [ 0.  2.  4.  0.  0.  0.  0.  0.  4.  0.  0.  0.  0.  0.]
nsamples 620
620 [ 0.  2.  4.  0.  0.  0.  0.  0.  4.  0.  0.  0.  0.  0.]
nsamples 720
720 [ 0.  2.  4.  0.  0.  0.  0.  0.  4.  0.  0.  0.  0.  0.]
nsamples 820
820 [ 0.  2.  4.  0.  0.  0.  0.  0.  4.  0.  0.  0.  0.  0.]
nsamples 920
920 [ 0.  2.  4.  0.  0.  0.  0.  0.  4.  0.  0.  0.  0.  0.]
nsamples 1020
1020 [ 0.  2.  4.  0.  0.  0.  0.  0.  4.  0.  0.  0.  0.  0.]
nsamples 1120
1120 [ 0.  2.  4.  0.  0.  0.  0.  0.  4.  0.  0.  0.  0.  0.]
nsamples 1220
1220 [ 0.  2.  4.  0.  0.  0.  0.  0.  4.  0.  0.  0.  0.  0.]
nsamples 1320
1320 [ 

In [156]:
shap_performance

[0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0]

In [147]:
exp = shap.KernelExplainer(f, np.zeros((1,10)))

In [148]:
exp.explain(x).effects

array([ 2.,  4.,  0.,  0.,  0.,  4.,  0.,  0.,  0.,  0.])

In [136]:
f(np.zeros((1,10)))

0.0