# Migrating to the new "Explanation" API

This notebook explains some of the differences between the old- and new-style shap API.

In short:

```python
shap_values = explainer.shap_values(X)  # Old style
shap_values = explainer(X)              # New style
```

In [1]:
# Create an example dataset and model
import xgboost

import shap

X, y = shap.datasets.adult(n_points=100)
model = xgboost.XGBClassifier().fit(X, y)
explainer = shap.TreeExplainer(model, X)

In older versions of shap, explanations are represented as simple numpy arrays and
calculated using the `.shap_values()` method:

In [2]:
shap_values = explainer.shap_values(X)
shap_values[:2]  # a numpy array

array([[-0.54854601,  0.01639348, -0.46476041,  0.85896822, -1.36168788,
        -0.64692199,  0.0254638 , -0.58422904, -0.02344483,  0.        ,
         0.1224989 ,  0.01079906],
       [-0.83802091,  0.01562196,  0.78349799, -1.10456323, -0.68524691,
        -0.84828204,  0.03734176, -0.86151311, -0.02564897,  0.        ,
        -0.56183428,  0.00415988]])

In newer versions of shap, explanations are represented with the `Explanation` object,
and are created by calling the explainer directly:

In [3]:
shap_values = explainer(X)
shap_values[:2]  # a shap.Explanation

.values =
array([[-0.54854601,  0.01639348, -0.46476041,  0.85896822, -1.36168788,
        -0.64692199,  0.0254638 , -0.58422904, -0.02344483,  0.        ,
         0.1224989 ,  0.01079906],
       [-0.83802091,  0.01562196,  0.78349799, -1.10456323, -0.68524691,
        -0.84828204,  0.03734176, -0.86151311, -0.02564897,  0.        ,
        -0.56183428,  0.00415988]])

.base_values =
array([-2.70354599, -2.70354599])

.data =
array([[27.,  4., 10.,  0.,  1.,  1.,  4.,  0.,  0.,  0., 44., 39.],
       [27.,  4., 13.,  4., 10.,  0.,  4.,  0.,  0.,  0., 40., 39.]])

The `Explanation` object tracks more information, such as the background dataset and the feature names.

The new-style plotting functions like `shap.plots.beeswarm` require `Explanation` objections.